### ISSUE TITLE
Doc build filled with `Base.IOError("stream is closed or unusable", 0)` exceptions

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimateMachine.jl#1190]
# Description

There are a lot of `Base.IOError("stream is closed or unusable", 0)` exceptions in the doc build, and this should be fixed.

## Additional context

Add any other reasons why this should be addressed.

# For CLIMA Developers

- [ ] This feature can be added (if it cannot be, explain why in a comment below -- lack of technical expertise, not relevant to the scope of this project, too ambitious)
- [ ] There is a timeline for when this feature can be implemented
- [ ] The feature has been (or will be) implemented (Please link the PR)

**Comment by jakebolewski** [comment]
It seems like the culprit here is `ClimateMachine` overriding the in-process global logger which conflicts with the execution of Literate (and Literates logging).  Disabling `ClimateMachine`'s global logging overload resolves the issue but we probalby have to brainstorm a way to make ClimateMachine's logging independent of the calling process global state.

Related #134
