### ISSUE TITLE
moisture bc question

### ISSUE THREAD

**Issue by trontrytel** [CliMA/ClimateMachine.jl#1435]
# Description

In the moisture boundary condition here:

https://github.com/CliMA/ClimateMachine.jl/blob/f3afd23226b49ab7a29d34ce94894197c708110d/src/Atmos/Model/bc_moisture.jl#L57-L61

Shouldn't the density flux be divided by the dry air specific humidity? Or are we omitting this because the dry air specific humidity is close to 1? I'm basing this on the notes I got from @yairchn. But I'm doing a lot of this and more when writing down the sources and sinks on `q_tot` from microphysics. So I'm asking so that I can be consistent there. 

![moist_bc_question](https://user-images.githubusercontent.com/1196696/89981000-e7dbd300-dc27-11ea-9ad7-b0add9f71596.jpeg)

@tapios , @szy21 @akshaysridhar ?

**Comment by trontrytel** [comment]
And a follow up question - Shouldn't there be a corresponding flux of total energy that comes from the changes in internal energy because of adding `q_tot` into the system?

**Comment by szy21** [comment]
I think the flux here corresponds to D(\rhoqt)/Dt. so following your derivation you will have the following (although I'm not confident with myself at all):

![IMG_7363](https://user-images.githubusercontent.com/11598433/90047199-5d768c00-dc86-11ea-9b9e-2828f5537a7d.jpg)

The diffusive total energy flux is calculated from the gradient of total enthalpy, which includes the changes in internal energy because of changing in `q_tot`. See Section 5.1.3 in the design doc. For microphysics sources and sinks, Section 4.3 may be helpful?

**Comment by tapios** [comment]
The density boundary source here is analogous to the source in Eq. (3.2) of the design doc. There is no dry-air density here. (We would never want to do such a thing as omitting a density factor just because on Earth right now, it's close to one. We want to be able to simulate early Earth, Titan, Mars, and your favorite exoplanet too!) And, as @szy21 said, you can see the dry-air  energy fluxes implied by `q_tot` changes in Eq. (5.8) in the design doc.

**Comment by trontrytel** [comment]
Thank you @szy21 and @tapios . I guess the variable name confused me With `nρd_q_tot` I thought that `ρ` was in front of the derivative. This looks good to me and I'll read the Section 5 again in the DDs. 

I have to think of what is my favourite exoplanet! I have to look for something with interesting precipitation...

**Comment by tapios** [comment]
> I have to think of what is my favourite exoplanet! I have to look for something with interesting precipitation...

Take one with two suns--makes radiation more interesting too! And methane rain, please. Microphysics is so much more fun when rain drops are ~1 cm in diameter.... :)
