### ISSUE TITLE
tictoc macro is not compatible with Revise

### ISSUE THREAD

**Issue by jkozdon** [CliMA/ClimateMachine.jl#1470]
Due to the error that is thrown by `@tic` helper function [`_tic`](https://github.com/CliMA/ClimateMachine.jl/blob/06cba1d963ff14738a06ba28890eee6866be16e6/src/Utilities/TicToc/TicToc.jl#L51-L70) revise cannot be used if the function modified interacts with the tictoc macros.

One options is to change this to a warning instead of an error.

**Comment by jkozdon** [comment]
@kpamnany Just assigned you since I think you originally wrote this macro.

**Comment by leios** [comment]
Ah, great! Thanks. I'll dig into this soon

**Comment by kpamnany** [comment]
😕  Um? I'm not sure I understand the issue. Are you saying that [this `throw`](https://github.com/CliMA/ClimateMachine.jl/blob/master/src/Utilities/TicToc/TicToc.jl#L55) creates a problem with Revise?

If so, is that because it happens at compile time? And if that's the case, we should perhaps insert code that does the `throw` rather than change it to a warning.
