### ISSUE TITLE
Rename `nodal_update_auxiliary_state!` for `MPIStateArray` methods #1421

### ISSUE THREAD

**Issue by christophernhill** [CliMA/ClimateMachine.jl#1474]
These changes are making a mess of our development branch!! 

Is there any way we can stop doing this sort of stuff. 

The function signature changes are a real pain and ambiguous and now we are discovering some subtle breakages Couldn't this have been done in a way that maintained some backwards compatibility. Overloading names and changing semantics of existing signatures makes it really hard to figure out how to fix!

**Comment by blallen** [comment]
I think the cause of the pain is that we now have `update_auxiliary_state!` calling `update_auxiliary_state!`. 

In the HBModel, we are spared this because we do this step with `update_auxiliary_state_gradient!` as follows 
https://github.com/CliMA/ClimateMachine.jl/blob/59d123150880f87824c3c87177fb0e9cf92b3d6f/src/Ocean/HydrostaticBoussinesq/HydrostaticBoussinesqModel.jl#L670-L681
The branch [1] @jm-c is using has the same thing inside the regular `update_auxiliary_state!`
```julia
function update_auxiliary_state!(
    dg::DGModel,
    m::OceanModel,
    Q::MPIStateArray,
    t::Real,
    elems::UnitRange,
)
```
that eventually calls 
```julia
nodal_update_auxiliary_state!(f!, dg, m, ct3d_dQ, t, elems)
```
which #1421 renamed to `update_auxiliary_state!`. I think this caused a weird chain where this line calls the full `update_auxiliary_state!` function instead of the specific one that applies `nodal_update_auxiliary_state!` (or `f!`).

@charleskawczynski, does this sound reasonable to you?

[1] https://github.com/jm-c/CLIMA/blob/jmc/split_explicit_draft/src/Ocean/SplitExplicit01/OceanModel.jl#L479

**Comment by charleskawczynski** [comment]
Regarding the pain, I apologize for the trouble this caused-- I had to fix my dev branches that conflicted with this, too. Also, I had looked around at several PRs/draft PRs before merging this-- I'm very open to yielding to other more important PRs when appropriate. Maybe it would be more transparent if these dev branches were converted to draft PRs? This way developers can more easily see what others are working on / how their PRs will impact others. FWIW, I did `deprecate` the old implementation.

On the technical side, I'm not sure I see the issue, all #1421 did was change a method name:

```julia
A = update_auxiliary_state!(dg::DGModel,balance_law::BalanceLaw,state_prognostic,t,elems,diffusive = false)
B = update_auxiliary_state!(f!,dg::DGModel,m::BalanceLaw,state_prognostic::MPIStateArray,t::Real,elems::UnitRange = dg.grid.topology.realelems;diffusive = false)
```

The framework calls `A` (which can be imported so that users can provide their own implementation), which by default calls `B` given a nodal/`Vars`-based method (`f!`).

If changing/splitting these names somehow makes things easier, I see no problem with it.

**Comment by christophernhill** [comment]
@charleskawczynski thanks. I think we are also still a little unclear how/why exactly this seems to be having an impact, whether there is some second order effect or something else name scoping wise going on that we haven't quite understood. 

Nevertheless I think the other thing that surprised me with the PR is the PR is named ```Rename `nodal_update_auxiliary_state!` for `MPIStateArray` methods```. It has ended up doing considerably more than I took the title to imply, and more than I think the initial plan was when it first appeared? Unfortunately I did not read below the fold before today. 

Perhaps we could also think about a way to make clearer when the scope of a PR starts to change. In this case possibly closing the PR and starting a new one with scope made clearer might have helped me - not sure?

**Comment by blallen** [comment]
Well, we do a lot more than just changing the auxiliary state in `A`, so that should probably be given a more general name. Currently we

1. directly update the aux state
2. perform an integral which is stored as an auxiliary variable
3. use an auxiliary balance law to take a derivative or integral
4. apply a filter
5. copy something from one MPI state array to another
6. create the universe

inside the `A` function. I'm not sure what a good name is, but I think it should imply that you can do basically anything here.

**Comment by christophernhill** [comment]
@blallen good point. A general thing that is a little unclear to me in kernels interface is when you have a full variable as an arg and when you have a throw away local copy passed to these functions. Could something related to that have been impacted strangeness here? 

Is this default 
```
elems::UnitRange = dg.grid.topology.realelems
```
significant. I am not sure we would have had that before?

**Comment by blallen** [comment]
> Is this default
> 
> ```
> elems::UnitRange = dg.grid.topology.realelems
> ```
> 
> significant. I am not sure we would have had that before?

@jkozdon can you clarify what happens if you don't have this? I know it's to avoid using ghost elements, but not all the details.

**Comment by jkozdon** [comment]
This is so that we don't have to communicate aux, but only update the ghost cells locally.

Before communication we update aux here on the real elements

https://github.com/CliMA/ClimateMachine.jl/blob/59d123150880f87824c3c87177fb0e9cf92b3d6f/src/Numerics/DGMethods/DGModel.jl#L151-L157

then update aux on the ghost here

https://github.com/CliMA/ClimateMachine.jl/blob/59d123150880f87824c3c87177fb0e9cf92b3d6f/src/Numerics/DGMethods/DGModel.jl#L236-L242

**Comment by jkozdon** [comment]
> I am not sure we would have had that before?

@christophernhill: This has been the behavior for about 5 months, since https://github.com/CliMA/ClimateMachine.jl/pull/855

**Comment by jkozdon** [comment]
> @jkozdon can you clarify what happens if you don't have this? I know it's to avoid using ghost elements, but not all the details.

What happens if this isn't like this is you will be updating aux on the ghost elements with old data (since we do not comm the aux data after initialization anymore).

**Comment by christophernhill** [comment]
@jkozdon thanks. The code here https://github.com/jm-c/CLIMA/blob/b8d416c482202c221b8441b1ecebbb151673f709/src/Ocean/SplitExplicit01/OceanModel.jl#L436 is all set with #855, but @jm-c is seeing some differences with trying to upgrade from about a month ago to present code - so we are fishing for clues....

**Comment by charleskawczynski** [comment]
[this](https://github.com/jm-c/CLIMA/blob/b8d416c482202c221b8441b1ecebbb151673f709/src/Ocean/SplitExplicit01/OceanModel.jl#L479) should now be a call to `update_auxiliary_state!`.

**Comment by christophernhill** [comment]
@charleskawczynski great - thanks. That sounds like it should help @jm-c

**Comment by jm-c** [comment]
@charleskawczynski  I tried it and it works ! Thanks.

**Comment by charleskawczynski** [comment]
@christophernhill is this still an issue? Or can we close this?

**Comment by christophernhill** [comment]
All set
