### ISSUE TITLE
Better naming scheme for output?

### ISSUE THREAD

**Issue by szy21** [CliMA/ClimateMachine.jl#1765]
### Description

Follow-up on the discussion with @jiahe23 @kpamnany @jakebolewski

Currently the output is named with an appended timestamp, which is inconvenient for scripted runs. What would be a better naming scheme?

**Comment by glwagner** [comment]
What's the motivation for having a naming scheme?

Here's my alternative viewpoint: I think it's best to refrain from imposing any naming scheme at all except when necessary. The main exception is when output must be split into multiple files, either because:

* computations are performed on distributed architectures (so we have `_rankXXXX`, etc)
* restrictions are imposed on the file size, either due to user dictate or for the purpose of having a practical default (eg, checkpointing)

This is the approach in Oceananigans. For checkpointing, we append user-provided prefixes with `_iterationXXXXXX` where `XXXXXX` is the model iteration the checkpoint pertains to. If users specify a `max_filesize`, we append user-provided prefixes with `_partX`, where the `X`s are ordered chronologically starting at 1.

Otherwise, user input is either respected or appended with the appropriate file extension.

**Comment by jiahe23** [comment]
> What's the motivation for having a naming scheme?
> 
> Here's my alternative viewpoint: I think it's best to refrain from imposing any naming scheme at all except when necessary. The main exception is when output must be split into multiple files, either because:
> 
> * computations are performed on distributed architectures (so we have `_rankXXXX`, etc)
> * restrictions are imposed on the file size, either due to user dictate or for the purpose of having a practical default (eg, checkpointing)
> 
> This is the approach in Oceananigans. For checkpointing, we append user-provided prefixes with `_iterationXXXXXX` where `XXXXXX` is the model iteration the checkpoint pertains to. If users specify a `max_filesize`, we append user-provided prefixes with `_partX`, where the `X`s are ordered chronologically starting at 1.
> 
> Otherwise, user input is either respected or appended with the appropriate file extension.

The current netcdf output is named as `ExperimentName_DiagnosticsType_TimestampOfSim.nc`. The timestamp is to differentiate new sim outputs (e.g., restart run) from existing data file but it is quite inconvenient for setting up auto postprocessing scriprs/notebooks. It also makes a lot more work for the weekly test and visualization. We might want to remove the timestamp but think about other ways of differentiate between simulations.

**Comment by valeriabarra** [comment]
Could another option be `ExperimentName_DiagnosticsType_NumerOfTimeStep.nc` ? 

I preferred this way in my past projects and then I could easily see at which time stamp I needed to restart the simulation after checkpointing. For instance, I would check in the `output-dir` which one was the highest number of the previously output simulation, e.g., 
 `ExperimentName_DiagnosticsType_500.nc` and then, I would continue the simulation with `--continue 500` (I don't know if this would fit your current implementation of continuing checkpointed solutions --- I haven't checked how it is done in CliMA yet)

**Comment by charleskawczynski** [comment]
I like the idea of using date/time. How about we use `DateTimeXX_MPIRankXX_iterationXX`? This should be relatively unique.

**Comment by kpamnany** [comment]
@valeriabarra: diagnostics output is in NetCDF files with an unlimited time dimension which is appended to at the time interval specified for diagnostics. There's only one file per run per diagnostics group. These file names are what this issue is about.

Our checkpoints use a different mechanism, writing the raw (prognostic and auxiliary) state variables to JLD2 files with the format `<ExperimentName>_checkpoint_mpirank%04d_num%04d.jld2` (yes, currently we save a file per MPI rank because parallel NetCDF is a headache we haven't tackled yet); you restart by re-running the experiment and specifying `--restart-from-num XX` where `XX` is the suffix after `num` in the checkpoint file name.

@charleskawczynski: I think the problem is:

> Currently the output is named with an appended timestamp, which is inconvenient for scripted runs.

If you want to run an experiment from a script and then run a second script that parses the diagnostics output (as the QA pipeline does), then figuring out the filename for the diagnostics output is difficult. Using date/time (which is basically the timestamp we have now) is the whole problem.

**Comment by valeriabarra** [comment]
Thanks for your detailed description @kpamnany ! 
So yes, the restart in CLiMA works in the same way I have implemented in the past, based on the output number. 
And yes, I do understand the problem with the timestamp as well

**Comment by kpamnany** [comment]
So basically, right now we have:
```julia
@sprintf(
    "%s_%s_%s",
    dgngrp.out_prefix,
    dgngrp.name,
    Settings.starttime,
)
```
Where `dgngrp.out_prefix` is the experiment-specified name and `dgngrp.name` is the name of the diagnostics group (e.g. `AtmosMassEnergyLoss`). If we remove `Settings.starttime` then the question becomes: do we simply overwrite any existing file?

My concern was that if we do that, then when you're doing a series of runs for which you want to retain the diagnostics output, you will end up using multiple output directories to avoid losing the old files, and then you usually end up with a bunch of `tmp/`, `tmp2/`, etc. directories and then you can't find what you want. Still, I guess remembering the timestamp is just as difficult.

So unless anyone else has a better idea, we'll fix this problem by simply removing the timestamp from the filename and overwriting any existing file.
