### ISSUE TITLE
Min node distance or average node distance in the Driver

### ISSUE THREAD

**Issue by valeriabarra** [CliMA/ClimateMachine.jl#1913]
### Description

I am looking to add new CL options in the Driver and I stumbled upon some definitions of nodal distance/grid size that puzzle me. 

In the `driver_configs.jl` file, what is exactly `(Δx, Δy, Δz)` on [this line](https://github.com/CliMA/ClimateMachine.jl/blob/7203cf0b5504e587717a1d65a4b0d9beb8d5100c/src/Driver/driver_configs.jl#L144)? 
For how we use it [later](https://github.com/CliMA/ClimateMachine.jl/blob/7203cf0b5504e587717a1d65a4b0d9beb8d5100c/src/Driver/driver_configs.jl#L177) it seems like it represents the average nodal distance or the node distance in case the nodes were all equidistant (in fact the formula `elemsize = Δx * polyorder_horz` makes sense to me only if `Δx` represented the distance between equidistant nodes).

But then later on, we actually print the grid information using the minimal nodal distance [min(Δ_horz)](https://github.com/CliMA/ClimateMachine.jl/blob/7203cf0b5504e587717a1d65a4b0d9beb8d5100c/src/Driver/driver_configs.jl#L205) computed as `min_node_distance(grid, HorizontalDirection())`, because as far as I know, we are indeed using LGL nodes, which are non-equidistant by definition. 

This might be only a matter of variable naming convention. If I did not misunderstand the meaning of these variables, then `Δx` could be called `Δx_ave` to be distinguished by `Δx`, which in the rest of the code represents the minimal (since it is not uniform) nodal distance. 

Besides the name of the variables, which could be a bit misleading, I am also puzzled by why we use equidistant nodes in the calculation of [brickrange](https://github.com/CliMA/ClimateMachine.jl/blob/7203cf0b5504e587717a1d65a4b0d9beb8d5100c/src/Driver/driver_configs.jl#L176) if we know that use non-equidistant LGL nodes in our spatial DG discretization. 

Any clarification would be much appreciated, thanks!

**Comment by jkozdon** [comment]
I *believe* that the motivation for `Δx, Δy, Δz` is as you said to give an average resolution per degree of freedom. I think this was to allow folks to transform between what they would have specified with a finite difference method and finite element method (specifying a LGL distance would be tough).

In some previous comparisons with finite difference methods, I've seen that the accuracy per degree of freedom is roughly the same for finite difference and finite element methods (assume the same order methods are used for both). From what I remember, DG you want to remove the "duplicate" points.

IF we did all our integrals exactly (which we don't) the choice of basis wouldn't matter. The LGL minimum node distance is just a way to estimate to get a rough scaling on how the extent of the eigenvalue spectrum scales with polynomial order. It's often said that the spectra scales like `1 / N^2` though there evidence that this is too conservative, maybe closer to `1 / N^1.75`; see [1] and [2]. If this is correct, then min LGL node distance is likely close but not perfect:
```julia
julia> using GaussQuadrature

julia> N = 1:9;

julia> l = [minimum(diff(legendre(n+1, both)[1])) for n in N];

julia> r = (log.(l[2:end]) - log.(l[1:end-1])) ./ (log.(N[1:end-1]) - log.(N[2:end]))
8-element Array{Float64,1}:
 1.0000000000000002
 1.4619842468875865
 1.6352215059075577
 1.7262327269049245
 1.7818492728035906
 1.8191436880827998
 1.8457905869028233
 1.865730755079601
```
last line is the fit between two points of the formula `Δ = C / N^r` (solving for `r` and eliminating `C`).

I think the handwavy argument for min LGL distance is that since LGL points are a good basis for interpolation and quadrature that the min distance controls the CFL.

If I remember correctly, the choice of basis shouldn't affect the spectrum (under exact arithmetic and integration), so using minimum node distance can only be an estimate of the spectra IF a well-conditioned basis is used (Legendre-Gauss or Legendre-Gauss-Lobatto) and using a bad basis (Equally spaced) will lead to a poor estimate. (Also, min node distance arguments fail if you choose to use a "modal" basis.)

[1]: https://www.sciencedirect.com/science/article/abs/pii/S0168927412001742
[2]: https://www-sciencedirect-com.libproxy.nps.edu/science/article/abs/pii/S0168927413000639

**Comment by valeriabarra** [comment]
Thanks @jkozdon for your detailed answers and references (by the way, I could only access ref. 1 you pointed to - ref. 2 asks for an NPS login, which I don't have).

My question though was not really regarding min nodal distance in the spectrum analysis using LGL nodes or other nodes for basis (I am well aware of the ill-conditioning of the Vandermonde matrix arising with equispaced grid points). I was just trying to understand why we use this `Δx` (that corresponds to an average nodal distance in case to equispaced points) for the construction of `brickrange`. And I wanted to make sure that other people also understand that we do not use equidistant nodes, because by asking this question around it seemed like this bit of code led some people believe that we do use equidistant nodes for our discretization.

**Comment by jkozdon** [comment]
> Thanks @jkozdon for your detailed answers and references (by the way, I could only access ref. 1 you pointed to - ref. 2 asks for an NPS login, which I don't have).

Fixed now. Sorry about that.

> My question though was not really regarding min nodal distance in the spectrum analysis using LGL nodes or other nodes for basis (I am well aware of the ill-conditioning of the Vandermonde matrix arising with equispaced grid points). I was just trying to understand why we use this `Δx` (that corresponds to an average nodal distance in case to equispaced points) for the construction of `brickrange`. And I wanted to make sure that other people also understand that we do not use equidistant nodes, because by asking this question around it seemed like this bit of code led some people believe that we do use equidistant nodes for our discretization.

Ahh... makes sense.  `Δx` is an effective resolution, and maybe just calling is `average resolution` or something like this would be better so it's not confused with `grid spacing`. Probably calling the `min(Δ_horz)` the `minimum LGL node distance` would be better too?

**Comment by valeriabarra** [comment]
Okay, thanks, clear now. 

Nah, I think it is not necessary to rename `min(Δ_horz)` as `minimum LGL node distance`, as long as it is clear to people that we use LGL nodes (that non equidistant by definition). 

It sounds like what is currently named `Δx` is what I need for what I was trying to do (add a CL option for resolution/number of elements). Thanks!

**Comment by charleskawczynski** [comment]
I would like to track that we should still change the print (from the first two links):
```julia
min(Δ_horz)             = %.2f m
```
to
```julia
ave(Δ_horz)             = %.2f m
```
So it's not mistakenly reported.

**Comment by valeriabarra** [comment]
@charleskawczynski you're saying that it is not usefl/effective to print the min node distance, but you'd rather print the average or effective element size? I do not see very useful to print the average nodal distance. That might lead even more people believe that we are using an equispaced grid, when we are not

**Comment by charleskawczynski** [comment]
Ah, I misread. I thought it corresponded to [this print](https://github.com/CliMA/ClimateMachine.jl/blob/7203cf0b5504e587717a1d65a4b0d9beb8d5100c/src/Driver/driver_configs.jl#L214). Ok, I'm fine with closing.

**Comment by valeriabarra** [comment]
Yeah, I will probably change that line you pointed to, now that I am adding effective resolution/number of elements as a CL option
