### ISSUE TITLE
Saturation adjustment fails with reasonable values

### ISSUE THREAD

**Issue by szy21** [CliMA/ClimateMachine.jl#1989]
### Description

When running the moist baroclinic wave, SA fails even though the input values seem reasonable. For example:

Setting tolerance to 0.1:
```
maxiter reached in saturation_adjustment:
Method=NewtonsMethod, e_int=11594.663171, ρ=0.931742, q_tot=0.006174, T=272.908738, maxiter=3, tol=71.750602
```

Setting tolerance to 1:
```
maxiter reached in saturation_adjustment:
Method=NewtonsMethod, e_int=10011.473560, ρ=0.929731, q_tot=0.006852, T=272.130054, maxiter=3, tol=717.506023
```

**Comment by tapios** [comment]
This is near the freezing point, where Newton iterations have trouble because of the discontinuity. We should simply exit without error when maxiter is reached. (We can also smooth the phase transition, and perhaps should do so one day. But for now simply exiting at maxiter would be preferable. Ideally we would do so with a warning. We have discussed this earlier, but then it was difficult to write out warnings. If that is still the case, simply ignore the lack of convergence at maxiter. This issue should not continue to hold us up.)

**Comment by szy21** [comment]
We have hacked into SA a little bit and it seems at one point during the iteration the temperature goes to NaN. But I'm not sure, the output is hard to understand.

@charleskawczynski Could we have an option that allows SA to exit at max iteration (without warnings if it is hard)? I know it is not ideal, but we want to test what really breaks the moist runs for now and this would be very helpful. Thanks!

**Comment by charleskawczynski** [comment]
I spoke with @bischtob about this. The "quick" fix to improve robustness is to use [this commit](https://github.com/CliMA/ClimateMachine.jl/commit/8c665bd0f294d454774a35c7e8e77fc7d9a61793) from [this branch](https://github.com/CliMA/ClimateMachine.jl/compare/ck/robust_thermo), which makes Regula Falsi method, which has a much more robust [convergence region](https://clima.github.io/ClimateMachine.jl/previews/PR1885/DevDocs/Common/Thermodynamics/Thermodynamics/#D-space) the default numerical method, and increases the maximum number of iterations to 10. These changes may make the simulation a bit slower, but SA should converge for _all_ reasonable input values.

I'm hoping to merge #1885 and investigate the performance-robustness tradeoff of different numerical methods so that we can get the best of both worlds.

Furthermore, I would recommend to not modify `error_on_non_convergence()` for two reasons:
 - It does not suppress the print statements, which will also severely slow down the solution
 - There will be no guarantees on the resulting temperature, which I've seen to reach NaNs given certain combinations of inputs.

**Comment by tapios** [comment]
Why are we continuing to make this complicated, @charleskawczynski? Other models use 1 fixed Newton iteration (e.g., NCAR). As you can see from @szy21's values, temperatures are essentially converged, despite the energy discontinuity. I see no point in going to regula falsi and many iterations to deal with the phase transition.  

Please make an option for no-fail exit at maxiter.

**Comment by tapios** [comment]
If you are concerned about NaNs, you can put a separate catch in there.

**Comment by charleskawczynski** [comment]
I agree with your suggestion, my recommendation was just for debugging. We can use the existing `Thermodynamics.error_on_non_convergence() = false` and `Thermodynamics.print_warning() = false` options. This will also remove the prints so that the simulation will not significantly slow down.

**Comment by szy21** [comment]
> I agree with your suggestion, my recommendation was just for debugging. We can use the existing `Thermodynamics.error_on_non_convergence() = false` and `Thermodynamics.print_warning() = false` options. This will also remove the prints so that the simulation will not significantly slow down.

Setting both `error_on_non_convergence` and `print_warning` to False works, thanks! Is this the final solution? If so I will close this issue.

**Comment by charleskawczynski** [comment]
Yes, I think we can close if that works.
