### ISSUE TITLE
Add unused tutorial

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimateMachine.jl#2033]
### Description

`tutorials/Atmos/burgers_single_stack_bjfnk.jl` was not included in the tutorials, so this code is not exercised. We should add it so that it's exercised.

**Comment by ilopezgp** [comment]
@charleskawczynski This file is a spin-off of `tutorials/Atmos/burgers_single_stack.jl` added by @Zhengyu-Huang to verify the implicit solver in a simple, single stack setting:

https://github.com/CliMA/ClimateMachine.jl/commit/a853f01da42bbe25cac44fb0fc31af7a315df532#diff-bc108d271239ee644428893ea010f6d72bb8173fc98542508db10d6f34850fe7

 I think it is a valuable addition to the code base, but you are right that we should exercise it. @Zhengyu-Huang could you verify that the implicit solver used here is the state-of-the-art version that we want? Could you add comments about the solver configuration, since this would be a step-by-step tutorial?
