### ISSUE TITLE
Slow AtmosModel when using balance-law problems

### ISSUE THREAD

**Issue by LenkaNovak** [CliMA/ClimateMachine.jl#2095]
### Description

The definition of variables as part of a balance law's problem (e.g. [here](https://github.com/CliMA/ClimateMachine.jl/blob/jh/testing-interface/interface/test_model.jl#L69) seems to slow down the pre-compilation 10 times in this unit test, compared to defining the same variables directly in the main balance law ( i.e.` aux.c` rather than `aux.hyperdiffusion.c`), even when using the problem kernels. I'm also seeing something that may be race conditions in the solution (some values correct to machine precision, and some 0 or tiny) if using the `aux.hyperdiffusion.c` form of variables. The `AtmosModel` uses the [same formulation](https://github.com/CliMA/ClimateMachine.jl/blob/jh/testing-interface/src/Atmos/Model/AtmosModel.jl#L470).

The time seems to be correlated with the allocations (10s with 20M versus 200s with 2G).

**Comment by kpamnany** [comment]
FYI: @simonbyrne and @charleskawczynski. We should discuss this, may be `VariableTemplates`?

**Comment by charleskawczynski** [comment]
It would be helpful if we had an MWE. Are we certain that commenting that one line causes the compilation overhead?

**Comment by charleskawczynski** [comment]
How can I run the test?

**Comment by LenkaNovak** [comment]
It's probably easiest to run it from the REPL: `include("interface/run_script.jl")`

**Comment by charleskawczynski** [comment]
It turned out that this was due to type instabilities, which we fixed on [this branch](https://github.com/CliMA/ClimateMachine.jl/commit/e374e0309a4bbb0bec8af2e6b7d72bf6364a8234). First, `FT` was not declared `const`, the second major piece missing was that `TestEquations` had non-concrete types, resulting in dynamic lookups for `vars_state` for all `TestEquations` properties.
