### ISSUE TITLE
Modifiable planet parameters

### ISSUE THREAD

**Issue by simonbyrne** [CliMA/ClimateMachine.jl#594]
Ideally we would allow defining new types representing new planets, e.g.
```julia
abstract type AbstractPlanet
end
struct Earth <: AbstractPlanet
end
planet_radius(::Earth) = 6.371e6

struct Jupiter <: AbstractPlanet
end
planet_radius(::Earth) = 69.911e6
```

This would require passing the `planet` object through all the functions. It would probably make sense to do that as part of #390.

Until we have that, the simplest option is to create a macro to redefine `Parameters` objects globally, i.e.
```julia
@updateparameter planet_radius 69.911e6
```
would expand to
```julia
Float64(::CLIMA.ParametersType.Parameter{:planet_radius}) = 69.911e6
Float32(::CLIMA.ParametersType.Parameter{:planet_radius}) = 69.911f6
```

**Comment by ali-ramadhan** [comment]
Out of curiosity, why dispatch on the planet type instead of defining a struct like
```julia
struct Planet{T}
    radius :: T
    ...
end

Earth = Planet(6371e3, ...)
Jupiter = Planet(69911e3, ...)
```

Dispatching feels like it might get messy once there are many planet properties beyond just the radius (rotation rate, surface gravity, etc.) but maybe dispatching on the planet type would better fit together with the rest of CliMA.jl.

**Comment by simonbyrne** [comment]
That is another option (but would still require passing the `planet` object in). I imagine they would be fairly similar, but there might be minor advantages to defining a type per planet as the constants would be known at compile time.

**Comment by ali-ramadhan** [comment]
Ah I see, that makes sense. But if we define the struct with a parametric type like `Planet{T}` and a user defines a new planet then the compiler should also know the type at compile time since it's all JIT compiled anyways, right?

I guess we usually take the struct approach as it feels easier for users to create an object
```julia
Earth = Planet(radius=6371e3)
```
rather than a new type
```julia
struct Earth <: AbstractPlanet end
planet_radius(::Earth) = 6371e3
```

Was just curious about your approach as it's not something I've considered for performance reasons.

**Comment by simonbyrne** [comment]
> Ah I see, that makes sense. But if we define the struct with a parametric type like `Planet{T}` and a user defines a new planet then the compiler should also know the type at compile time since it's all JIT compiled anyways, right?

Yes, the compiler will know the types, but the question is whether it will know the _values_. In all reality, there will probably be little difference, the main cases would be where it can evaluate expressions at compile time. (the downside is that we would pay compilation overhead for defining new planets, but that is pretty small in the big scheme of things).

**Comment by ali-ramadhan** [comment]
Ah right, thanks for the explanation!

**Comment by tapios** [comment]
@simonbyrne If I can add a wishlist: It would be nice to have a default `planet` struct, e.g., for Earth, but then have easy ways to *rescale* parameters, e.g,
``
@rescale_parameter planet_radius 1//10
``
which would multiply the radius by 1//10. We'll need such transformations frequently.

**Comment by charleskawczynski** [comment]
Does #962 close this?

**Comment by tapios** [comment]
It basically does. You can close the issue. However, it would be good to add an example (e.g., int he tutorials) showing how to run a GCM with rescaled parameters. For example, include a Held-Suarez setup with planetary rotation rate increased by a factor 2 and Earth radius decreased by a factor 2.

**Comment by charleskawczynski** [comment]
I think the [CLIMAParameters docs](https://clima.github.io/CLIMAParameters.jl/dev/#Overriding-defaults) basically covers this.
