### ISSUE TITLE
Any tagged releases like v0.1.0 planned?

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/ClimateMachine.jl#665]
Just curious.

Would be helpful to be able to reference specific versions and if the package gets registered then it'll be super easy to install in the Julia REPL without having to worry about whether master has changed.

Releases can be tagged as "pre-release" to signify that they're not production ready if that's a concern. Stable API isn't expected until v1.0.0 with semantic versioning anyways.

**Comment by tapios** [comment]
Yes, we should have a tagged release as soon as we can. (We talked briefly about it.) It would be good not just to reference it, but also to have a stable version into which we can begin to integrate all the components (parameterization schemes etc.) we need. 

Here's what I think we need for the atmosphere model for a v0.1.0 release:

- [ ] 1D IMEX default for timestepping in LES and GCM configurations
- [ ] Default and well tested horizontally explicit timestepping schemes with default Courant numbers on which the timestep choice can be based (in the configuration files) [we want users to be able to specify a horizontal discretization and shield them from details of timestepping choices]
- [ ] Cleaned up and completed interfaces for boundary conditions, and integration of atmosphere boundary condition in driver/configuration setup
- [ ] Clean up of atmosphere model (more "physical" file structure for defining equations of motion, e.g., define mass, momentum, energy, and water balances each in one file, rather than spreading the respective sources and fluxes over several files)
- [ ] Have one central location (directory) for collecting files with free parameters from the various model components
- [ ] Have a simple way of adjusting planet parameters (e.g., run default Earth parameters except with 1/10 Earth radius, or 10 times rotation rate, with rescaling of default parameters specified from driver)

Perhaps @simonbyrne and @kpamnany can work with everyone else to figure out what is doable by when?

**Comment by bischtob** [comment]
I can also help coordinate.

**Comment by charleskawczynski** [comment]
[First release complete!](https://github.com/CliMA/ClimateMachine.jl/releases/tag/v0.1.0)🎉
