### ISSUE TITLE
Show random seed for experiments.

### ISSUE THREAD

**Issue by jkozdon** [CliMA/ClimateMachine.jl#977]
In this [slurm ci](https://github.com/climate-machine/CLIMA/pull/938#issuecomment-615415685) Held-Suarez failed. I believe it was due to the random numbers being generated but I have no way to check (it passed locally and matched master when I forced the random seed).

I would recommend that any experiments that require random numbers display the seed they use.

For MPI jobs we need to display each ranks random seed.

This is related to closed issue #792

**Comment by kpamnany** [comment]
This is a little tricky. First, I think that at this point we cannot make the typical `rand(Uniform(-1e-3, 1e-3))` call on the GPU -- all experiments that have a need to do this currently use `init_on_cpu = true`. If/when this is fixed, a solution for the GPU side will be needed.

On the CPU, each Julia thread has its own RNG state which means that we need to display each thread's seed, e.g. by printing `Random.default_rng().seed`. Unfortunately, there is (intentionally) no way to force a snippet of code to run on a particular thread.

If we turn this around (i.e. instead of displaying the seed, we force a specific seed, as is [recommended for reproducibility](https://docs.julialang.org/en/v1/stdlib/Random/index.html#Reproducibility-1)) then a possible way to do this would be to add a command line option like `--fix-rng-seed` or `--reproducible` which will make the Driver do something like:
```
using Random
using MPI
using Base.Threads
rank = MPI.Comm_rank(MPI.COMM_WORLD)
for tid in 1:nthreads()
    s = parse(Int, string(rank) * string(tid))
    seed!(Random.default_rng(tid), s)
end
```

Thoughts?

Cc: @vchuravy

**Comment by jkozdon** [comment]
Mainly I just wanted to raise the issue (as #792 did) that for debugging and testing reproducibility is nice. Though I certainly understand why this is not needed / desirable for real experiments.

On caveat is that I'm guessing it would have been useful for those working on Held-Suarez to know what parameters caused failure(?).

**Comment by jkozdon** [comment]
> If we turn this around (i.e. instead of displaying the seed, we force a specific seed, as is [recommended for reproducibility](https://docs.julialang.org/en/v1/stdlib/Random/index.html#Reproducibility-1)) then a possible way to do this would be to add a command line option like `--fix-rng-seed` or `--reproducible` which will make the Driver do something like.

This seems reasonable to me.
